### ISSUE TITLE
Compiler Warnings

### ISSUE THREAD

**Issue by joan-domingo** [futurice/freesound-android#126]
As a first task I thought I could fix the compiler warnings. Is it fine?

> :app:compileDebugJavaWithJavac
**Note: C:\Users\Joan\AndroidStudioProjects\freesound-android\app\src\main\java\com\futurice\freesound\feature\search\SearchSnackbar.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.**

> :app:compileDebugNdk UP-TO-DATE
:app:compileDebugSources
:app:incrementalDebugAndroidTestJavaCompilationSafeguard
:app:javaPreCompileDebugAndroidTest
:app:compileDebugAndroidTestJavaWithJavac
:app:compileDebugAndroidTestNdk UP-TO-DATE
:app:compileDebugAndroidTestSources
:app:incrementalDebugUnitTestJavaCompilationSafeguard UP-TO-DATE
:app:javaPreCompileDebugUnitTest
:app:compileDebugUnitTestJavaWithJavac
**Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: C:\Users\Joan\AndroidStudioProjects\freesound-android\app\src\test\java\com\futurice\freesound\common\utils\CollectionUtilsTest.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.**

**Comment by peter-tackage** [comment]
Sure! Check out the README for a short description of the PR contribution guidelines and how to get the project setup.

**Comment by joan-domingo** [comment]
Fixed and merged
