### ISSUE TITLE
RxJava 2 CompositeDisposable usage

### ISSUE THREAD

**Issue by VasileUngureanu** [futurice/freesound-android#130]
Hi, from what i read recently sounds that if we want to use CompositeDisposable then we need to use subscribeWith and DisposableObserver (and other consumers for each (single, maybe, completable ...)).

An example here:
https://github.com/amitshekhariitbhu/RxJava2-Android-Samples/blob/master/app/src/main/java/com/rxjava2/android/samples/ui/operators/DisposableExampleActivity.java

You tested if your current implementation works?

**Comment by peter-tackage** [comment]
I believe that's only relevant if you are subscribing with a single Observer `public final void subscribe(Observer<? super T> observer`, rather than the overloaded versions with individual `Consumer` instances which we use.

Did you find a bug with the current implementation?
