### ISSUE TITLE
Communication between fragment viewmodel and adapter view model

### ISSUE THREAD

**Issue by ViperAlpha** [futurice/freesound-android#174]
How is it possible to make a communication between these too?

[related question](https://stackoverflow.com/questions/49246648/communication-in-android-between-main-view-and-recyclerviewadapter-with-mvvm)

**Comment by peter-tackage** [comment]
Perhaps you've already solved this. I would imagine that you would need a shared data source/model. It should be scoped to the largest scope of the populating Views (probably the Fragment). This is a fairly standard way to approach data sharing between Views, if I've understood your need correctly. Hope that helps.

**Comment by ViperAlpha** [comment]
Thanks for your answer! I solved it by sharing one view model for both of them. :)
