### ISSUE TITLE
Using `OnceAndStream` and  `Stream` suffix?

### ISSUE THREAD

**Issue by tomaszpolanski** [futurice/freesound-android#60]
Types of Observables in Rx 2 does not help with reasoning about if an observable emits any event on subscription and if it ever completes.

How about using those to suffixes: `OnceAndStream` and  `Stream`.

`Once` we do not need to as `Single` and `Maybe` will give us this information.

**Comment by peter-tackage** [comment]
Sounds reasonable. I don't think that I have employed a naming very strictly so far in the app.

**Comment by tomaszpolanski** [comment]
Ok, then I'll update the readme and change the existing code.
