### ISSUE TITLE
Add more complex scenarious

### ISSUE THREAD

**Issue by VasileUngureanu** [futurice/freesound-android#70]
First of all Thanks for such a clean project. I was looking very long fora good implementation of MVVM with RxJava and this project is the best that i found!
You have plans to complete him with some more complex things like permissions, services, db, orientation changes... I mean their position in MVVM architecture.

Thanks!

**Comment by tomaszpolanski** [comment]
Hey,
we plan to add to the app more features and share our idea how one could create reactive architecture. 
Currently, we are mainly setting up the infrastructure for the app. Soon after will come more advanced integrations.
Still, we are trying to make this application to bring user value. We want it to be, first and foremost, useful to the user, and this we will try to do while applying the best practices we know.

Cheers

**Comment by peter-tackage** [comment]
We'll be addressing this in individual features; so closing.
