### ISSUE TITLE
Gradle project sync failed on release proguard settings

### ISSUE THREAD

**Issue by VasileUngureanu** [futurice/freesound-android#73]
Error:
Error:(56, 0) Cannot convert the provided notation to a File or URI: [./proguard-rules/android-support-rules.pro, ./proguard-rules/autovalue-rules.pro, ./proguard-rules/okhttp3-rules.pro, ./proguard-rules/picasso-rules.pro, ./proguard-rules/retrofit2-rules.pro, ./proguard-rules/retrolambda-rules.pro, ./proguard-rules/rxjava2-rules.pro, ./proguard-rules/okio-rules.pro, ./proguard-rules/picasso-rules.pro].
The following types/formats are supported:
  - A String or CharSequence path, for example 'src/main/java' or '/usr/include'.
  - A String or CharSequence URI, for example 'file:/usr/include'.
  - A File instance.
  - A URI or URL instance.
<a href="openFile:/home/ungvas/AndroidDev/Projects/freesound-android/app/build.gradle">Open File</a>

Line:   
proguardFiles getDefaultProguardFile('proguard-android.txt'), releaseProguardFiles

P.S. If comment this line build work :) 

Thanks

Ubuntu 16.04

**Comment by peter-tackage** [comment]
This occurs when using `classpath 'com.android.tools.build:gradle:2.2.0'`, it behaves correctly using `2.1.3`.

**Comment by peter-tackage** [comment]
We need to define a solution for abstractly defining a list of Proguard file which works on the latest Gradle build.

**Comment by VasileUngureanu** [comment]
Hmmm I use 2.2.1

**Comment by peter-tackage** [comment]
My guess is that the API changed slightly after `2.1.3` which has broken it for us. Stick with `2.1.3` for now.
