### ISSUE TITLE
After importing freesound code style setting we get several codestyles. Which one to use? 

### ISSUE THREAD

**Issue by VasileUngureanu** [futurice/freesound-android#74]
Thanks!

**Comment by tomaszpolanski** [comment]
@peter-tackage We should at least rename them ;)

**Comment by VasileUngureanu** [comment]
You try square codestyles? With kotlin look great...

**Comment by tomaszpolanski** [comment]
With code style, it comes down to personal preference. For now, we should choose some general style guidelines and if we find something we see as valuable, we can integrate it into the project.

In square code style, do you see anything worthwhile to be integrated in our current one?

**Comment by peter-tackage** [comment]
Yeah, I've merged a change which only has the one style. Please use that @VasileUngureanu

**Comment by VasileUngureanu** [comment]
@tomaszpolanski Square code style make code more compact. I think you need to test it by yourself to see differences ))
@peter-tackage Got it ))
