### ISSUE TITLE
Make time based features testable

### ISSUE THREAD

**Issue by tomaszpolanski** [futurice/freesound-android#83]
We should have an easy way to use TimeSkipScheduler to use in tests but still be able to have computation scheduler in the application.

**Comment by peter-tackage** [comment]
I think we are still waiting for a new RxAndroid release so we can override schedulers with plugins, rather than SchedulerProvider abstraction.

**Comment by tomaszpolanski** [comment]
I was thinking of a combination of time() Scheduler done the similar way as the plugins. We do not need the change to RxAndroid
