### ISSUE TITLE
Persistence model

### ISSUE THREAD

**Issue by VasileUngureanu** [futurice/freesound-android#94]
Hi.
I use your project as main reference to my production app and now i need to implement persistence (local database). 
You not add it yet (but i hope you will add soon) and i want to ask how would you will implement it in the future.
How i see it: 
If we have API and it is consumed directly in DataModel then for local database we also need to have an Datasource/Repository class (for managing local database) that will be also consumed in DataModel directly.
And if we need to interact API and database (for example to save remote data in local database) we will need to do it in DataModel.
 
Or?

We need to have an additional repository class/es that will manage both API and local database. 
And DataModel will consume only that repository class/es. (More like traditional repository pattern that we find in most examples).

P.S. Yesterday was released RxRelay with RxJava2 support, how you look at replacing Subjects with RxRelay? 

Thanks and Sorry for these stupid questions!

**Comment by peter-tackage** [comment]
The short answer for your first question is that I would tend towards using the second approach. 

Regarding RxRelay, I personally don't have a strong opinion on whether or not to include it. I see the the benefits and I've used other Subject alternatives on other project. At the same time, Subjects work well enough for us, given that you are careful enough with them, but replacing them is more a matter of priority for me.

**Comment by VasileUngureanu** [comment]
Thanks! OK then if we use 2nd variant then what will be the role of "DataModel"? We have ViewModel -> DataModel -> DataManager. Not too many classes?

**Comment by tomaszpolanski** [comment]
What does the `DataManager` do?
About the layer of the application, we usually have something like ViewModel -> DataModel -> Repository -> Network. 
This still can vary depending on the size of an application.

**Comment by VasileUngureanu** [comment]
@tomaszpolanski DataManager is "Repository" in layers you describe.
I just a little confuse about role difference between DataManager and Repository.

 "This still can vary depending on the size of an application." This is the answer.
Thanks!
